FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

# npm build saves to a /build folder
# nginx needs files in /usr/share/nginx/html to serve them
COPY --from=build /app/build /usr/share/nginx/html

# default port for nginx
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
