name: Build Backend

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: "Where to push the image to 'ECR' or 'HUB'"
        options:
          - ECR
          - HUB
        default: ECR

jobs:
  build-and-push:
    uses: ./.github/workflows/wc-build-push.yaml
    with:
      repository: langserve
      dockerfile: Dockerfile
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}