name: Build and Push
run-name: Build and Push - ${{ github.event.inputs.destination }}

on:
  workflow_dispatch:
    inputs:
      destination:
        type: choice
        description: "Where to push the image to 'ECR' or 'HUB'"
        options:
          - ECR
          - HUB
        default: ECR

jobs:
  build-and-push-backend:
    uses: ./.github/workflows/wc-build-push.yaml
    with:
      repo: langserve
      image_tag: latest
      dockerfile: Dockerfile
      context: ./backend
      destination: ${{ inputs.destination }}
    secrets: inherit

  build-and-push-frontend:
    uses: ./.github/workflows/wc-build-push.yaml
    with:
      repo: langserve-frontend
      image_tag: latest
      dockerfile: Dockerfile.prod
      context: ./frontend
      destination: ${{ inputs.destination }}
    secrets: inherit
