name: Deploy
run-name: Deploy - ${{ github.event.inputs.stack }}

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        description: "Which infra to deploy"
        options:
          - backend
          - frontend
          - common
          - backend-frontend
        default: common

jobs:
  deploy-common:
    if : ${{ github.event.inputs.stack == 'common' }}
    name: Common
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: common
      command: apply
    secrets: inherit

  deploy-backend:
    if: ${{ inputs.stack == 'backend' || inputs.stack == 'backend-frontend' }}
    name: Backend
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: backend
      command: apply
    secrets: inherit

  deploy-frontend:
    if: ${{ inputs.stack == 'frontend' || inputs.stack == 'backend-frontend' }}
    name: Frontend
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: frontend
      command: apply
    secrets: inherit
