name: Deploy
run-name: Deploy - ${{ github.event.inputs.stack }}

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        description: "Which infra to build and push"
        options:
          - backend
          - frontend
          - common
          - backend-frontend
        default: common

jobs:
  deploy-common:
    if : ${{ github.event.inputs.stack == 'common' }}
    name: Common
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: common
    secrets: inherit

  deploy-backend:
    if: ${{ github.event.inputs.stack == 'backend' || github.event.inputs.stack == 'backend-frontend' }}
    name: Backend
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: backend
    secrets: inherit

  deploy-frontend:
    if: ${{ github.event.inputs.stack == 'frontend' || github.event.inputs.stack == 'backend-frontend' }}
    name: Frontend
    uses: ./.github/workflows/wc-deploy.yaml
    with:
      dir: frontend
    secrets: inherit
