name: wc - build and push

on: 
  workflow_call:
    inputs:
      repository:
        description: 'ECR Repository'
        required: true
        type: string
      image_tag:
        description: 'Image tag'
        type: string
      dockerfile:
        description: 'Dockerfile name'
        type: string
      destination:
        type: string
        description: "Where to push the image to 'ECR' or 'HUB'"
        default: ECR
  
jobs:
  build-and-push-ecr:   
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04  
    steps:  
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Setup AWS ECR Details
        if: inputs.destination == 'ECR'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: inputs.destination == 'ECR'
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: inputs.destination == 'HUB'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        env:
          URL: ${{ steps.ecr.outputs.registry }} if inputs.destination == 'ECR' else 'felixsteph'
          REPO: ${{inputs.repository}}
          TAG: ${{inputs.image_tag}}
          FILE: ${{inputs.dockerfile}}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $URL/$REPO:$TAG
        
