name: wc - build and push

on: 
  workflow_call:
    inputs:
      repository:
        description: 'ECR Repository'
        required: true
        type: string
      image_tag:
        description: 'Image tag'
        type: string
        default: latest
      dockerfile:
        description: 'Dockerfile name'
        type: string
        default: Dockerfile
      destination:
        type: string
        description: "Where to push the image to 'ECR' or 'HUB'"
        default: ECR
  
jobs:
  build-and-push-ecr:   
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04  
    steps:  
      - name: Checkout
        uses: actions/checkout@v2 

      - name: echo
        run: echo ${{ secrets.AWS_REGION }}
        
      - name: Setup AWS ECR Details
        if: inputs.destination == 'ECR'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        if: inputs.destination == 'ECR'
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{inputs.repository}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ${{inputs.dockerfile}} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{inputs.image_tag}}
